version: '3.4'

services:
  front:
    container_name: medcard-front
    image: chillingspree/medcard-nst:front
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: "http://localhost:53125"