version: '3.4'

services:
  med-card-database:
    container_name: med-card-database
    image: postgres
    restart: always
    volumes:
      - med-card-database-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "mc-storage"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
    ports:
    - 8484:5432
    expose: 
    - '8484'

  med-card-webapi:
    container_name: med-card-webapi
    image: efimka/med-card-webapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      med-card-database:
        condition: service_started
    ports:
    - 53125:80
  front:
    container_name: medcard-front
    image: chillingspree/medcard-nst:front
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: "http://localhost:53125"
    depends_on:
      med-card-webapi:
        condition: service_started

volumes:
  med-card-database-volume:
