export const infoParameters = [
  {
    name: "RBC",
    info: {
      fullName: "Эритроциты",
      measure: "млн/мкл (106/мкл)",
      menNormMin: 4.3,
      menNormMax: 5.7,
      womenNormMin: 3.8,
      womenNormMax: 5.1,
    },
  },
  {
    name: "MCV",
    info: {
      fullName: "Средний объём эритроцитов",
      measure: "фл (фемтолитр)",
      menNormMin: 80.0,
      menNormMax: 99.0,
      womenNormMin: 81.0,
      womenNormMax: 100.0,
    },
  },
  {
    name: "HGB",
    info: {
      fullName: "Гемоглобин",
      measure: "г/дл",
      menNormMin: 13.2,
      menNormMax: 17.3,
      womenNormMin: 11.7,
      womenNormMax: 15.5,
    },
  },
  {
    name: "MCH",
    info: {
      fullName: "Среднее количества гемоглобина в 1 эритроците",
      measure: "пг (пикограмм)",
      menNormMin: 27.0,
      menNormMax: 34.0,
      womenNormMin: 27.0,
      womenNormMax: 34.0,
    },
  },
  {
    name: "CP",
    info: {
      fullName: "Реактивный белок",
      measure: "мг/л",
      menNormMin: 3.0,
      menNormMax: 5.0,
      womenNormMin: 3.0,
      womenNormMax: 5.0,
    },
  },
  {
    name: "PLT",
    info: {
      fullName: "Тромбоциты",
      measure: "x10^9/л",
      menNormMin: 180.0,
      menNormMax: 320.0,
      womenNormMin: 180.0,
      womenNormMax: 320.0,
    },
  },
  {
    name: "HCT",
    info: {
      fullName: "Гематокрит",
      measure: "-",
      menNormMin: 0.360,
      menNormMax: 0.520,
      womenNormMin: 0.360,
      womenNormMax: 0.520,
    },
  },
  {
    name: "MCHC",
    info: {
      fullName: "Средняя концентрация гемоглобина в эритроцитах",
      measure: "г/дл",
      menNormMin: 32.0,
      menNormMax: 37.0,
      womenNormMin: 32.0,
      womenNormMax: 36.0,
    },
  },
  {
    name: "RET",
    info: {
      fullName: "Ретикулоциты",
      measure: "%",
      menNormMin: 0.67,
      menNormMax: 1.92,
      womenNormMin: 0.59,
      womenNormMax: 2.07,
    },
  },

  {
    name: "WBC",
    info: {
      fullName: "Лейкоциты",
      measure: "тыс/мкл (103 клеток/мкл)",
      menNormMin: 4.5,
      menNormMax: 11.0,
      womenNormMin: 4.5,
      womenNormMax: 11.0,
    },
  },

  {
    name: "MPV",
    info: {
      fullName: "Средний объем тромбоцитов",
      measure: "фл",
      menNormMin: 8.0,
      menNormMax: 15.0,
      womenNormMin: 8.0,
      womenNormMax: 15.0,
    },
  },
  {
    name: "RFV",
    info: {
      fullName: "",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "ESR",
    info: {
      fullName: "Cкорость Оседания Эритроцитов",
      measure: "%",
      menNormMin: 0.0,
      menNormMax: 12.0,
      womenNormMin: 0.0,
      womenNormMax: 12.0,
    },
  },
  {
    name: "ALAT",
    info: {
      fullName: "Аланинаминотрансфераза",
      measure: "Ед/л",
      menNormMin: 0.0,
      menNormMax: 31.0,
      womenNormMin: 0.0,
      womenNormMax: 41.0,
    },
  },
  {
    name: "АсАТ",
    info: {
      fullName: "Аспартатаминотрансфераза (в сыворотке крови)",
      measure: "Ед/л",
      menNormMin: 0.0,
      menNormMax: 29.0,
      womenNormMin: 0.0,
      womenNormMax: 31.0,
    },
  },
  {
    name: "Bilirubin",
    info: {
      fullName: "Общий билирубин",
      measure: "мг/дл",
      menNormMin: 0.3,
      menNormMax: 1.2,
      womenNormMin: 0.3,
      womenNormMax: 1.2,
    },
  },
  {
    name: "Glucose",
    info: {
      fullName: "Глюкоза",
      measure: "мкмоль/л",
      menNormMin: 11.6,
      menNormMax: 28.0,
      womenNormMin: 6.6,
      womenNormMax: 26.0,
    },
  },
  {
    name: "GlycatedHemoglobin",
    info: {
      fullName: "Гликированный гемоглобин",
      measure: "%",
      menNormMin: 3.0,
      menNormMax: 6.0,
      womenNormMin: 3.0,
      womenNormMax: 6.0,
    },
  },
  {
    name: "Iron",
    info: {
      fullName: "Железо",
      measure: "мкмоль/л",
      menNormMin: 11.6,
      menNormMax: 28.0,
      womenNormMin: 6.6,
      womenNormMax: 26.0,
    },
  },
];

export const arrayNameIndicators = [
  "RBC",
  "MCV",
  "HGB",
  "MCH",
  "CP",
  "PLT",
  "HCT",
  "MCHC",
  "RET",
  "WBC",
  "MPV",
  "RFV",
  "ESR",
  "ALAT",
  "ASAT",
  "Bilirubin",
  "Glucose",
  "GlycatedHemoglobin",
  "Iron",
];
