export const infoParameters = [
  {
    name: "RBC",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.85,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "MCV",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "HGB",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "MCH",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "CP",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "PLT",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "HCT",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "MCHC",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "RET",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },

  {
    name: "WBC",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },

  {
    name: "MPV",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "RFV",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "ESR",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "ALAT",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "ASAT",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "Bilirubin",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "Glucose",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "GlycatedHemoglobin",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
  {
    name: "Iron",
    info: {
      fullName: "Эритроциты",
      measure: "%",
      menNormMin: 3.5,
      menNormMax: 3.8,
      womenNormMin: 3.2,
      womenNormMax: 3.6,
    },
  },
];

export const arrayNameIndicators = [
  "RBC",
  "MCV",
  "HGB",
  "MCH",
  "CP",
  "PLT",
  "HCT",
  "MCHC",
  "RET",
  "WBC",
  "MPV",
  "RFV",
  "ESR",
  "ALAT",
  "ASAT",
  "Bilirubin",
  "Glucose",
  "GlycatedHemoglobin",
  "Iron",
];
